#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'

cmd, app = ARGV
root = ENV['DOKKU_ROOT']

def fail(message)
  puts message
  exit 1
end

if cmd && cmd.start_with?("domains")
  fail "You must specify an app name" if app.nil? || app.strip.empty?
  fail "App #{app} does not exist" if !Dir.exist?(approot)

  approot = File.join(root, app)
  domainfile = File.join(approot, 'DOMAINS')

  if !File.exist?(domainfile)
    puts "-----> Creating #{domainfile}"
    FileUtils.touch(domainfile)
  end
end

case cmd
when 'domains'
  puts File.read(domainfile)
when 'domains:set'
  newdomains = ARGV[2..-1]
  fail "Usage: dokku domains:set APP DOMAIN1 [DOMAIN2 ...]\nMust specify a DOMAIN." if newdomains.empty?

  File.open(domainfile, 'w') { |file| file.write(newdomains.join(" ")) }
  system "dokku deploy #{app}"
when 'help'
  puts STDIN.read
  puts <<-EOF
    domains <app>                                   display the domains for an app
    domains:set <app> DOMAIN1 [DOMAIN2 ...]         set one or more domains
  EOF
end
