#!/usr/bin/env ruby
require 'erb'
require 'pathname'

app = ARGV[0]
root = ENV['DOKKU_ROOT']
domainspath = File.join(root, app, 'DOMAINS')
vhostpath = File.join(root, 'VHOST')

exit unless File.exists?(domainspath)

vhost = File.read(vhostpath).strip
hostname = "#{app.sub('/','-')}.#{vhost} " + File.read(domainspath).strip
port = File.read(File.join(root, app, 'PORT')).strip
ssl = File.join(root, app, 'ssl')
use_ssl = File.exists?(File.join(ssl, 'server.crt')) && File.exists?(File.join(ssl, 'server.key'))

# write app/nginx.conf
template = File.open(File.join(Pathname.new(__FILE__).dirname, 'nginx.conf.erb'), 'rb').read
File.open(File.join(root, app, 'nginx.conf'), 'w') { |file| file.write(ERB.new(template).result) }

# write app/URL
url = "#{use_ssl ? 'https' : 'http'}://#{hostname.split(" ")[0]}"
File.open(File.join(root, app, 'URL'), 'w') { |file| file.write(url) }
