#!/usr/bin/env ruby
require 'erb'
require 'pathname'

def write(filename, text)
  File.open(File.join(root, app, filename), 'w') { |file| file.write(text) }
end

app = ARGV[0]
root = ENV['DOKKU_ROOT']

hostname = File.read(File.join(root, app, 'DOMAINS'))
port = File.read(File.join(root, app, 'PORT'))
ssl = File.join(root, app, 'ssl')
use_ssl = File.exists?(File.join(ssl, 'server.crt')) && File.exists?(File.join(ssl, 'server.key'))

# write app/nginx.conf
template = File.open(File.join(Pathname.new(__FILE__).dirname, 'nginx.conf.erb'), 'rb').read
write('nginx.conf', ERB.new(template).result)

# write app/URL
url = "#{use_ssl ? 'https' : 'http'}://#{hostname.split(" ")[0]}"
write('URL', url)
